language: node_js
cache:
  directories:
    - node_modules
install: npm install
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
      node_js:
        - 8
        - 9
    - stage: deploy
      script: bash ./travis/deploy.sh
      node_js: 9
env:
  global:
    - ENCRYPTION_LABEL: "af862fa96d3e"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
